version: "2"
services:
  app:
    restart: always
    build: web
    env_file: web/.ENV
    environment:
      - DOCKER=true
    volumes:
      - .:/usr/app/
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    image: mongo
    volumes_from:
      - mongodata
    ports:
      - "27017:27017"
  mongodata:
    image: tianon/true
    volumes:
      - /data/db